services:

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - ${MINIO_API_PORT}:${MINIO_API_PORT}
      - ${MINIO_UI_PORT}:${MINIO_UI_PORT}
    volumes:
      - minio_data:/data
    command: minio server --address ":${MINIO_API_PORT}" --console-address ":${MINIO_UI_PORT}" /data
    restart: always

  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - MLFLOW_S3_ENDPOINT_URL=http://minio:${MINIO_API_PORT}
    ports:
      - ${MLFLOW_PORT}:${MLFLOW_PORT}
    command: mlflow server --host 0.0.0.0 --port ${MLFLOW_PORT}
    volumes:
      - mlflow_data:/mlflow
    restart: always

  trocr_api:
    build:
      dockerfile: trocr/api/Dockerfile
      args:
        MODEL_NAME: ${MODEL_NAME}
    container_name: trocr_api
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - api_network
  
  trocr_bot:
    build:
      dockerfile: trocr/bot/Dockerfile
    container_name: trocr_bot
    depends_on:
      - trocr_api
    networks:
      - api_network

volumes:
  minio_data:
  mlflow_data:

networks:
  api_network:
    driver: bridge